language: dart
sudo: false
dart:
  - stable
  - dev
dart_task:
- dartfmt
- dartanalyzer: --fatal-warnings lib
- test: --platform vm
- test: --platform chrome
- test: --platform dartium
  install_dartium: true

matrix:
  allow_failures:
    - dart: dev
      dart_task:
        dartfmt
    - dart_task:
        test: --platform chrome
