name: rational
version: 0.1.6
author: Alexandre Ardhuin <alexandre.ardhuin@gmail.com>
description: A simple package to deal with rational numbers
homepage: https://github.com/a14n/dart-rational
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dev_dependencies:
  browser: '>=0.10.0 <0.11.0'
  unittest: '>=0.11.0 <0.12.0'
