name: rational
version: 0.3.0
author: Alexandre Ardhuin <alexandre.ardhuin@gmail.com>
description: A simple package to deal with rational numbers
homepage: https://github.com/a14n/dart-rational
environment:
  sdk: '>=2.0.0-dev.66.0 <2.0.0'
dev_dependencies:
  test: ^1.2.0
